# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='player_command.proto',
  package='',
  serialized_pb=_b('\n\x14player_command.proto\"S\n\x11RequestIdentifier\x12\x0e\n\x06\x63ookie\x18\x01 \x02(\x04\x12\x16\n\x0erequestor_guid\x18\x02 \x02(\x04\x12\x16\n\x0erequestor_name\x18\x03 \x02(\t\"\xcd\x01\n\x10PlayerCommandMsg\x12*\n\x0ereq_identifier\x18\x01 \x02(\x0b\x32\x12.RequestIdentifier\x12\x11\n\tstop_play\x18\x02 \x01(\x08\x12:\n\x10new_song_request\x18\x03 \x01(\x0b\x32 .PlayerCommandMsg.NewSongRequest\x1a>\n\x0eNewSongRequest\x12\x11\n\tsong_name\x18\x01 \x02(\t\x12\x19\n\x0eposition_in_ms\x18\x02 \x01(\r:\x01\x30\"\xa4\x01\n\x15PlayerCommandReplyMsg\x12*\n\x0ereq_identifier\x18\x01 \x02(\x0b\x32\x12.RequestIdentifier\x12\x12\n\nreq_status\x18\x02 \x02(\x08\x12\x17\n\x0freq_status_desc\x18\x03 \x02(\t\x12\x17\n\x0fis_song_playing\x18\x04 \x02(\x08\x12\x19\n\x11\x63urrent_song_path\x18\x05 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUESTIDENTIFIER = _descriptor.Descriptor(
  name='RequestIdentifier',
  full_name='RequestIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cookie', full_name='RequestIdentifier.cookie', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestor_guid', full_name='RequestIdentifier.requestor_guid', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestor_name', full_name='RequestIdentifier.requestor_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=107,
)


_PLAYERCOMMANDMSG_NEWSONGREQUEST = _descriptor.Descriptor(
  name='NewSongRequest',
  full_name='PlayerCommandMsg.NewSongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='song_name', full_name='PlayerCommandMsg.NewSongRequest.song_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position_in_ms', full_name='PlayerCommandMsg.NewSongRequest.position_in_ms', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=315,
)

_PLAYERCOMMANDMSG = _descriptor.Descriptor(
  name='PlayerCommandMsg',
  full_name='PlayerCommandMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_identifier', full_name='PlayerCommandMsg.req_identifier', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop_play', full_name='PlayerCommandMsg.stop_play', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_song_request', full_name='PlayerCommandMsg.new_song_request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PLAYERCOMMANDMSG_NEWSONGREQUEST, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=315,
)


_PLAYERCOMMANDREPLYMSG = _descriptor.Descriptor(
  name='PlayerCommandReplyMsg',
  full_name='PlayerCommandReplyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_identifier', full_name='PlayerCommandReplyMsg.req_identifier', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_status', full_name='PlayerCommandReplyMsg.req_status', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_status_desc', full_name='PlayerCommandReplyMsg.req_status_desc', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_song_playing', full_name='PlayerCommandReplyMsg.is_song_playing', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_song_path', full_name='PlayerCommandReplyMsg.current_song_path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=482,
)

_PLAYERCOMMANDMSG_NEWSONGREQUEST.containing_type = _PLAYERCOMMANDMSG
_PLAYERCOMMANDMSG.fields_by_name['req_identifier'].message_type = _REQUESTIDENTIFIER
_PLAYERCOMMANDMSG.fields_by_name['new_song_request'].message_type = _PLAYERCOMMANDMSG_NEWSONGREQUEST
_PLAYERCOMMANDREPLYMSG.fields_by_name['req_identifier'].message_type = _REQUESTIDENTIFIER
DESCRIPTOR.message_types_by_name['RequestIdentifier'] = _REQUESTIDENTIFIER
DESCRIPTOR.message_types_by_name['PlayerCommandMsg'] = _PLAYERCOMMANDMSG
DESCRIPTOR.message_types_by_name['PlayerCommandReplyMsg'] = _PLAYERCOMMANDREPLYMSG

RequestIdentifier = _reflection.GeneratedProtocolMessageType('RequestIdentifier', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTIDENTIFIER,
  __module__ = 'player_command_pb2'
  # @@protoc_insertion_point(class_scope:RequestIdentifier)
  ))
_sym_db.RegisterMessage(RequestIdentifier)

PlayerCommandMsg = _reflection.GeneratedProtocolMessageType('PlayerCommandMsg', (_message.Message,), dict(

  NewSongRequest = _reflection.GeneratedProtocolMessageType('NewSongRequest', (_message.Message,), dict(
    DESCRIPTOR = _PLAYERCOMMANDMSG_NEWSONGREQUEST,
    __module__ = 'player_command_pb2'
    # @@protoc_insertion_point(class_scope:PlayerCommandMsg.NewSongRequest)
    ))
  ,
  DESCRIPTOR = _PLAYERCOMMANDMSG,
  __module__ = 'player_command_pb2'
  # @@protoc_insertion_point(class_scope:PlayerCommandMsg)
  ))
_sym_db.RegisterMessage(PlayerCommandMsg)
_sym_db.RegisterMessage(PlayerCommandMsg.NewSongRequest)

PlayerCommandReplyMsg = _reflection.GeneratedProtocolMessageType('PlayerCommandReplyMsg', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERCOMMANDREPLYMSG,
  __module__ = 'player_command_pb2'
  # @@protoc_insertion_point(class_scope:PlayerCommandReplyMsg)
  ))
_sym_db.RegisterMessage(PlayerCommandReplyMsg)


# @@protoc_insertion_point(module_scope)
