#ifndef WAVPLAYERALSA_PLAYER_EVENTS_IFC_H_
#define WAVPLAYERALSA_PLAYER_EVENTS_IFC_H_

#include <string>
#include <stdint.h>

/*
Player events are events that are generated by the player, and should be published to the outside world
*/

namespace wavplayeralsa {

	class PlayerEventsIfc {

	public:

		virtual void NewSongStatus(const std::string &songName, uint64_t startTimeMs, double speed) = 0;
		virtual void NoSongPlayingStatus() = 0;


	};


}

#endif // WAVPLAYERALSA_PLAYER_EVENTS_IFC_H_